txt = input("Digite a informação: ")
print("Num? {}".format(txt.isalnum()))
print("Alpha? {}".format(txt.isalpha()))
print("Ascii? {}".format(txt.isascii()))
print("Digit? {}".format(txt.isdigit()))
print("Lower? {}".format(txt.islower()))
print("Decimal? {}".format(txt.isdecimal()))
print("Identifier? {}".format(txt.isidentifier()))
print("Numeric? {}".format(txt.isnumeric()))
print("Printable? {}".format(txt.isprintable()))
print("Space? {}".format(txt.isspace()))
print("Upper? {}".format(txt.isupper()))
